// Generated by CoffeeScript 1.3.1
(function() {
  var LinearTransform;

  LinearTransform = (function() {

    LinearTransform.name = 'LinearTransform';

    function LinearTransform() {}

    LinearTransform.prototype._k = 1;

    LinearTransform.prototype._l = 0;

    LinearTransform.prototype.k = function(factor) {
      if (!factor) {
        return this._k;
      }
      return this._k = factor;
    };

    LinearTransform.prototype.l = function(offset) {
      if (!offset) {
        return this._l;
      }
      return this._l = offset;
    };

    LinearTransform.prototype.map = function(x) {
      return this._k * x + this._l;
    };

    LinearTransform.prototype.invert = function(y) {
      return (y - this._l) / this._k;
    };

    module.exports = LinearTransform;

    return LinearTransform;

  })();

}).call(this);
